<?php /**  @var $block \Newbury\FacebookChat\Block\FacebookChat */ ?>
<?php if(empty($block->getPageId())) return; ?>
<script>
    (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = 'https://connect.facebook.net/<?= $block->getLocale() ?>/sdk/xfbml.customerchat.js#xfbml=1&version=v2.12&autoLogAppEvents=1';
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
</script>
<div class="fb-customerchat"
     page_id="<?= $block->getPageId() ?>">
</div>